# This file is generated by device/lge/mako/setup-makefiles.sh

# Pick up overlay for features that depend on non-open-source files
DEVICE_PACKAGE_OVERLAYS := vendor/lge/mako/overlay

$(call inherit-product, vendor/lge/mako/mako-vendor-blobs.mk)
